jobs:
  - name: Data Ingestion and Transformation Pipeline
    timeout_seconds: 3600
    max_concurrent_runs: 1
    tasks:
      - task_key: bronze_consumer_ingest
        description: Ingest Consumer Data to Bronze
        existing_cluster_id: your-cluster-id
        notebook_task:
          notebook_path: /Repos/your-repo-path/bronze/consumer_bronze
        timeout_seconds: 1800

      - task_key: bronze_avocado_ingest
        description: Ingest Avocado Data to Bronze
        existing_cluster_id: your-cluster-id
        notebook_task:
          notebook_path: /Repos/your-repo-path/bronze/avocado_bronze
        timeout_seconds: 1800

      - task_key: bronze_fertilizer_ingest
        description: Ingest Fertilizer Data to Bronze
        existing_cluster_id: your-cluster-id
        notebook_task:
          notebook_path: /Repos/your-repo-path/bronze/fertilizer_bronze
        timeout_seconds: 1800

      - task_key: bronze_purchase_ingest
        description: Ingest Purchase Data to Bronze
        existing_cluster_id: your-cluster-id
        notebook_task:
          notebook_path: /Repos/your-repo-path/bronze/purchase_bronze
        timeout_seconds: 1800

      - task_key: silver_consumer
        description: Transform Consumer Data to Silver
        existing_cluster_id: your-cluster-id
        notebook_task:
          notebook_path: /Repos/your-repo-path/silver/consumer_silver
        depends_on:
          - task_key: bronze_consumer_ingest
        timeout_seconds: 1800

      - task_key: silver_avocado
        description: Transform Avocado Data to Silver
        existing_cluster_id: your-cluster-id
        notebook_task:
          notebook_path: /Repos/your-repo-path/silver/avocado_silver
        depends_on:
          - task_key: bronze_avocado_ingest
        timeout_seconds: 1800

      - task_key: silver_fertilizer
        description: Transform Fertilizer Data to Silver
        existing_cluster_id: your-cluster-id
        notebook_task:
          notebook_path: /Repos/your-repo-path/silver/fertilizer_silver
        depends_on:
          - task_key: bronze_fertilizer_ingest
        timeout_seconds: 1800

      - task_key: silver_purchase
        description: Transform Purchase Data to Silver
        existing_cluster_id: your-cluster-id
        notebook_task:
          notebook_path: /Repos/your-repo-path/silver/purchase_silver
        depends_on:
          - task_key: bronze_purchase_ingest
        timeout_seconds: 1800

      - task_key: gold
        description: Generate Gold Data
        existing_cluster_id: your-cluster-id
        notebook_task:
          notebook_path: /Repos/your-repo-path/gold/generate_gold
        depends_on:
          - task_key: silver_consumer
          - task_key: silver_avocado
          - task_key: silver_fertilizer
          - task_key: silver_purchase
        timeout_seconds: 1800
    schedule:
      quartz_cron_expression: "0 10 ? * MON *"
      timezone_id: "Your/Timezone"
